FROM debian:11@sha256:6f519a81440354a85eb592c5f32109ab80605f6b892455983a6f618bf87fabe9

ARG VOSK_BUILD_JOBS=3

COPY bullseye-snapshot.sources.list /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        g++ \
        bzip2 \
        unzip \
        make \
        wget \
        git \
        python3 \
        python3-pip \
        python3-wheel \
        python3-setuptools \
        python3-cffi \
        zlib1g-dev \
        patch \
        cmake \
        xz-utils \
        automake \
        autoconf \
        libtool \
        pkg-config \
        sudo \
        g++-mingw-w64-i686 \
        g++-mingw-w64-x86-64 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /opt/kaldi \
    && git clone https://github.com/alphacep/openfst \
    && cd openfst \
    && git checkout 18e94e63870ebcf79ebb42b7035cd3cb626ec090 \
    && autoreconf -i \
    && CXX=x86_64-w64-mingw32-g++-posix CXXFLAGS="-O3 -ftree-vectorize -DFST_NO_DYNAMIC_LINKING" \
        ./configure --prefix=/opt/kaldi/local \
        --enable-shared --enable-static --with-pic --disable-bin \
        --enable-lookahead-fsts --enable-ngram-fsts --host=x86_64-w64-mingw32 \
    && make -j ${VOSK_BUILD_JOBS} \
    && make install

RUN cd /opt/kaldi \
    && git clone -b v0.3.20 --single-branch https://github.com/xianyi/OpenBLAS \
    && cd OpenBLAS \
    && make HOSTCC=gcc BINARY=64 CC=x86_64-w64-mingw32-gcc ONLY_CBLAS=1 DYNAMIC_ARCH=1 TARGET=NEHALEM USE_LOCKING=1 USE_THREAD=0 -j ${VOSK_BUILD_JOBS} \
    && make PREFIX=/opt/kaldi/local install

RUN cd /opt/kaldi \
    && git clone -b v3.2.1  --single-branch https://github.com/alphacep/clapack \
    && mkdir clapack/BUILD \
    && cd clapack/BUILD \
    && cmake -DCMAKE_C_COMPILER_TARGET=x86_64-w64-mingw32 -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc-posix -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_CROSSCOMPILING=True .. \
    && make -C F2CLIBS/libf2c \
    && make -C BLAS \
    && make -C SRC \
    && find . -name *.a -exec cp {} /opt/kaldi/local/lib \;

RUN cd /opt/kaldi \
    && git clone -b vosk-android --single-branch https://github.com/alphacep/kaldi \
    && git -C kaldi checkout 8b7fecf92b329b7253d9d1cd97898c8b13f9aef3 \
    && cd kaldi/src \
    && CXX=x86_64-w64-mingw32-g++-posix CXXFLAGS="-O3 -ftree-vectorize -DFST_NO_DYNAMIC_LINKING" ./configure --shared --mingw=yes --use-cuda=no \
        --mathlib=OPENBLAS_CLAPACK \
        --host=x86_64-w64-mingw32 --openblas-clapack-root=/opt/kaldi/local \
        --fst-root=/opt/kaldi/local --fst-version=1.8.0 \
    && make -j ${VOSK_BUILD_JOBS} depend \
    && make -j ${VOSK_BUILD_JOBS} online2 lm rnnlm
